services:
  locust:
    build:
      context: .
      dockerfile: Dockerfile_headless
      args:
        UID: 1000
        GID: 1000
    container_name: locust_headless
    tty: true
    volumes:
      - ./locust_benchmark_scripts:/locust/locust_benchmark_scripts
      - ./dataset:/locust/dataset
      - ./raw_dataset:/locust/raw_dataset
      - ./zipf_dataset:/locust/zipf_dataset
      - ./results_headless:/locust/results_headless
      - ./locust_script.py:/locust/locust_script.py
      - ./requests:/locust/requests
