services:
  locust:
    build:
      context: .
      dockerfile: Dockerfile_web
      args:
        UID: 1000
        GID: 1000
    container_name: locust_web
    tty: true
    ports:
      - "8089:8089/tcp"
    volumes:
      - ./locust_benchmark_scripts:/locust/locust_benchmark_scripts
      - ./benchmark_dataset:/locust/benchmark_dataset
      - ./results:/locust/results
      - ./benchmark_raw_dataset:/locust/benchmark_raw_dataset
#    command:
#      - locust -f locust_benchmark_scripts/locust_random_client.py --csv /locust/results/results