FROM python:3.13.2-slim

ARG UID
ARG GID

WORKDIR /locust
COPY dataset ./bencbenchmark_dataset
COPY raw_dataset ./benchmark_raw_dataset
COPY locust_benchmark_scripts ./locust_benchmark_scripts
COPY requests ./requests
COPY requirements.txt .
COPY locust_script.py .

RUN addgroup --gid $GID locustgroup && \
    adduser --uid $UID --gid $GID --disabled-password locustuser

RUN mkdir "results_headless"
RUN pip install -r requirements.txt

# Use the user after installing the requiremets
USER locustuser

CMD python locust_script.py