FROM python:3.13.2-slim

ARG UID
ARG GID

RUN addgroup --gid $GID locustgroup && \
    adduser --uid $UID --gid $GID --disabled-password locustuser

WORKDIR /locust

COPY requirements.txt .
COPY locust_benchmark_scripts ./locust_benchmark_scripts
COPY benchmark_dataset ./benchmark_dataset
COPY benchmark_raw_dataset ./benchmark_raw_dataset
COPY requests ./requests

RUN mkdir results


EXPOSE 8089/tcp
RUN pip install -r requirements.txt

CMD locust -f locust_benchmark_scripts/locust_random_client.py --csv /locust/results/results
