[package]
name = "sctp_benchmarking_script"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = {path = "../utils"}
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"